### ISSUE TITLE
R7 - Make use of new Capability-Annotations [PAXWEB-1044]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1314]
**[Marc Schlegel](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:bf96723a-fc46-44ad-a1c6-9916df7773c4)** created **[PAXWEB-1044](https://ops4j1.jira.com/browse/PAXWEB-1044)** 

At the moment capabilities are managed with the maven-bundle-plugin within the pom.

With [RFP-167](https://github.com/osgi/design/blob/master/rfps/rfp-0167-Manifest-Annotations.pdf) there the annotations currently provided by bnd-annotations will be "official". This RFP will be part of R7.

All Require-/Provide-Capability instructions should be handled by those annotations, which would also make this stuff independent from the used build-tool.

---

**Fixed in:** future
Votes: 0, Watches: 1

---
**Referenced issues**

**is related from:**
* #1530 - OSGi capabilities are missing [PAXWEB-1251]
* #1354 - Upgrade to OSGi R7 [PAXWEB-1181]

**Comment by grgrzybek** [comment]
Because of the JavaEE API jar bundle problems (there are many JavaEE/JakartaEE/Glassfish/JBoss/Geronimo/SMX API jars), I'm closing this issue for now - Pax Web uses cap/req headers where needed and possible. Pax Web 8 works and provides "fragment bundles" for the javax.* API jars to add the Provide-Capability headers where needed and required by e.g., Aries CDI or JAX-RS.
