### ISSUE TITLE
Make "default servlet" configurable [PAXWEB-1245]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1526]
**[Grzegorz Grzybek](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:9c7cd322-6f60-46ab-9235-bab9ac2f59f6)** created **[PAXWEB-1245](https://ops4j1.jira.com/browse/PAXWEB-1245)** 

See [https://stackoverflow.com/questions/59377956/how-to-disable-the-default-servlet-in-karaf](https://stackoverflow.com/questions/59377956/how-to-disable-the-default-servlet-in-karaf)<br /> I'm (now, without checking) not sure if default servlet can be simply disabled globally/per context. Could be worth trying if it's not against specification.

---

Votes: 0, Watches: 2

**Comment by grgrzybek** [comment]
In Pax Web 8 it's clear:
* For Whiteboard scenario, no default servlet is registered, because the "context" underneath is not "full" (for example, in Jetty, it's not a WebAppContext, but a specialized version of ServletContextHandler.
* For WAB scenario, default servlet is **always** registered, because that's what expected by Servlets 4 specification. You can however install your own servlet (either named `default` or mapped to `/` - or both).
