### ISSUE TITLE
Upgrade to Tomcat 9.0.37 [PAXWEB-1267]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1546]
**[Stephan Siano](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:b67216a0-b10d-4720-bdc5-2945ed3f820d)** created **[PAXWEB-1267](https://ops4j1.jira.com/browse/PAXWEB-1267)** 

There has been a security advisory for Tomcat 9.0.36<br /> Important: WebSocket DoS CVE-2020-13935<br /> Moderate: HTTP/2 DoS CVE-2020-13934

---

**Affects:** 7.3.8
**Fixed in:** 8.0.0, 7.3.12
Votes: 0, Watches: 2

**Comment by jbonofre** [comment]
pax-web-features has to be updated to define new expected contract by Tomcat. I will do it for next releases.

**Comment by grgrzybek** [comment]
In Pax Web 8 I've simply added `<_contract>!*</_contract>` to get rid of `osgi.contract;osgi.contract=JavaServlet` requirement.
Tomcat got the contracts with https://bz.apache.org/bugzilla/show_bug.cgi?id=64540 and apache/tomcat#306

I understand the idea of _contracts_, though I find it quite awkward to use, especially if you develop a project with unit/integration/pax-exam tests. For example jakarta.servlet/jakarta.servlet-api artifact, which is the _canonical_ Servlet API exports all the required packages, but doesn't expose JavaServlet _capability_. There are no hundreds of bundle combinations from which you can compose "JavaServlet" capability provider. You just need one bundle.

I know that generally, with [JavaEE contracts](http://docs.osgi.org/reference/portable-java-contracts.html) you have APIs that consist of multiple JARs and I don't want to simply get rid of them. Because Pax Web 7 repackages Tomcat (in Pax Web 7 with TIPI and directly in Pax Web 8), we can get rid of the contracts in Pax Web - at least that's how I did it in Pax Web 8.

**Comment by jbonofre** [comment]
@grgrzybek yeah, let me do it for the release, that's acceptable indeed. Thanks, I'm doing it.
