### ISSUE TITLE
org.osgi.service.http.context exported version should be 1.1.0

### ISSUE THREAD

**Issue by jbonofre** [ops4j/org.ops4j.pax.web#1607]
Currently, `org.osgi.service.http.context` is exported with version 1.0.0 in Pax Web 7.3.x. Starting from R7, it should be 1.1.0.

**Comment by grgrzybek** [comment]
True, but 7.3 is not fully compliant even with R6... Thought the package could be at that version. Customer bundles relying on `1.0` will still work (assuming `[1.0,2.0)` range). It wouldn't work otherwise ;).
So :+1:

**Comment by jbonofre** [comment]
@grgrzybek I guess you meant "not fully compliant with R7" right ? I think for just package version it's acceptable and should work for both R6 and R7 users ;)

**Comment by grgrzybek** [comment]
I really meant R6, not R7. Pax Web 7 (any version) doesn't implement Whiteboard specification from OSGi CMPN R6 properly... That's why I started this Pax Web 8 effort.
These are the issues which (after I started checking them) made me realize that complete rewrite of the Whiteboard model is needed:
* ops4j/org.ops4j.pax.web#1414
* ops4j/org.ops4j.pax.web#1413

**Comment by jbonofre** [comment]
@grgrzybek at you mean for whiteboard (I thought generally speaking). Agree.
