### ISSUE TITLE
RFC 5929 tls-unique

### ISSUE THREAD

**Issue by jweu** [ops4j/org.ops4j.pax.web#1649]
There is a rfc5929 "Channel Bindings for TLS" but it's difficult to get 'tls-unique' from the HttpServletRequest. I found this information at BCSSLConnection.getChannelBinding("tls-unique"). This should be a request attribute because it's a mandatory information at rfc7030.

**Comment by grgrzybek** [comment]
Thanks for reporting! Let me investigate.

**Comment by grgrzybek** [comment]
@jweu by:
> This should be a request attribute because it's a mandatory information at rfc7030

do you refer to any particular Java-related specification? (JavaEE, OSGi, ...)?

**Comment by Neustradamus** [comment]
Any progress on it?

After the jabber.ru MITM, it is time to add it:
- https://notes.valdikss.org.ru/jabber.ru-mitm/
- https://snikket.org/blog/on-the-jabber-ru-mitm/
- https://www.devever.net/~hl/xmpp-incident
- https://blog.jmp.chat/b/certwatch

Little details, to know easily:
- tls-unique for TLS =< 1.2 (RFC5929)
- tls-server-end-point =< 1.2 + 1.3 (RFC5929)
- tls-exporter for TLS = 1.3 (RFC9266)

Thanks in advance.

**Comment by grgrzybek** [comment]
Thanks for the links @Neustradamus but presence or absence of certain HttpServletRequest attributes is not a responsibility of Pax Web, but the underlying Servlet API implementation. 

See chapter `3.11. SSL Attributes`, we can get these attributes:
* jakarta.servlet.request.cipher_suite
* jakarta.servlet.request.key_size
* jakarta.servlet.request.ssl_session_id
* jakarta.servlet.request.X509Certificate

But nothing about `tls-unique`...

You should maybe report this here: https://github.com/jakartaee/servlet/issues ?

**Comment by Neustradamus** [comment]
@grgrzybek: Thanks for your comment :)

2014-09-25 is the date of the ticket importation, link after.

@edburns has done a ticket:
- https://github.com/jakartaee/servlet/issues/107
- Original GitHub place: https://github.com/javaee/servlet-spec/issues/107
- This issue was imported from java.net JIRA SERVLET_SPEC-107

2015-12-16: This ticket has been cloned by MyHat95111:
- https://github.com/jakartaee/servlet/issues/151
- Original GitHub place: https://github.com/javaee/servlet-spec/issues/151
- This issue was imported from java.net JIRA SERVLET_SPEC-151

Ron Monzillo, Mark Thomas, @DDvO have commented.

@gregw has done a change on the ticket.

We are at the end of 2023, it is time to look for security!

After the jabber.ru MITM, it is time to add it:
- https://notes.valdikss.org.ru/jabber.ru-mitm/
- https://snikket.org/blog/on-the-jabber-ru-mitm/
- https://www.devever.net/~hl/xmpp-incident
- https://blog.jmp.chat/b/certwatch

Little details, to know easily:
- tls-unique for TLS =< 1.2 (RFC5929)
- tls-server-end-point =< 1.2 + 1.3 (RFC5929)
- tls-exporter for TLS = 1.3 (RFC9266)

cc: @ops4j, @javaee, @jakartaee teams.

**Comment by Neustradamus** [comment]
@grgrzybek: I think that you must to keep opened and only close it when it will be integrated...

**Comment by Neustradamus** [comment]
@grgrzybek: I think that you must to keep opened and only close it when it will be integrated...

And please comment on the jakartaee/servlet ticket that it is needed here.

**Comment by grgrzybek** [comment]
> it is needed here

Isn't it needed in the entire Java ecosystem? Pax Web is just µfraction of it ;)

> only close it when it will be integrated

Extrapolating the history of this feature, it may take many years...
