### ISSUE TITLE
Can not change session cookie name

### ISSUE THREAD

**Issue by rhierlmeier** [ops4j/org.ops4j.pax.web#1745]
Changing the session cookie name in etc/org.ops4j.pax.web.cfg is not working.
I implemented a itest for this feature:

https://github.com/rhierlmeier/paxweb8-test/blob/main/paxweb8-itest/src/test/java/de/hierlmeier/paxweb8test/itests/SessionCookieTest.java

PAX-WEB version 8.0.6
Karaf- version 4.4.1
Java version: 8u342

**Comment by grgrzybek** [comment]
For WAB scenario (pax-web-extender-war) the problem was the assumption of JSESSIONID in case the web.xml (or other metadata for the WAB) didn't contain session configuration - so JSESSIONID was chosen despite the `org.ops4j.pax.web.session.cookie.name` PID configuration.

I'm checking the Whiteboard (pax-web-extender-whiteboard) scenario now. I also found some server wrapper leak when changing session configuration.

**Comment by grgrzybek** [comment]
And thanks @rhierlmeier for https://github.com/rhierlmeier/paxweb8-test/blob/main/paxweb8-itest/src/test/java/de/hierlmeier/paxweb8test/itests/SessionCookieTest.java - do you mind if I create a Pax Web test based on it?

**Comment by rhierlmeier** [comment]
> And thanks @rhierlmeier for https://github.com/rhierlmeier/paxweb8-test/blob/main/paxweb8-itest/src/test/java/de/hierlmeier/paxweb8test/itests/SessionCookieTest.java - do you mind if I create a Pax Web test based on it?

Please reuse the test.
