### ISSUE TITLE
[8.0.x] OsgiServletContextClassLoader(TCCL) could use inner-class loaded from uninstalled bundles

### ISSUE THREAD

**Issue by qianwch** [ops4j/org.ops4j.pax.web#1771]
It is a quite strange problem.
When using TCCL to load inner Classes, it could happen after uninstalling and reinstalling the bundle:
1. The parent class is loaded by the ClassLoader of the reinstalled bundle.
2. The inner class is loaded by the ClassLoader of the uninstalled bundle.

```java
Class<?> implCls = Class.forName(
          HelloApiWrapper.class.getName()+"$MyHello", false, Thread.currentThread().getContextClassLoader());
api = (HelloApi) implCls.newInstance(); //Could fail: NoClassDefFoundError / ClassCastException
```
For application developers, it could rarely happen. But If we use libraries such as spring that could use TCCL to load classes, it just could happen.
Here is a POC project for this recurring the issue, tested in karaf 4.4.1 pax-web 8.0.9/9.0.0:
```bash
# build the test-project
tar xf tcc-bug-poc
cd tcc-bug-poc
mvn clean install
# install the test-project
cd apache-karaf-4.4.1/bin
./karaf
#install whiteboard 8.0.9
feature:repo-add mvn:org.ops4j.pax.web/pax-web-features/8.0.9/xml/features
feature:install pax-web-http-jetty
feature:install pax-web-whiteboard
feature:repo-add mvn:org.example/the-poc-feature/LATEST/xml/features
feature:install tccl-bug-poc
# Test the app, we could get "MyHello: Hi World !", and in karaf console the bundle ids will be printed
curl http://localhost:8181/hello1
# Then in karaf we uninstall and reinstall the test project
feature:uninstall tccl-bug-poc
feature:install tccl-bug-poc
# Then test again, we could get ClassCastException, and the bundle ids will be printed, you will notice that the is org.example.the-lib1 id is of the uninstalled version.
curl http://localhost:8181/hello1
```

[tccl-bug-poc.tar.gz](https://github.com/ops4j/org.ops4j.pax.web/files/9632739/tccl-bug-poc.tar.gz)

**Comment by grgrzybek** [comment]
#1760 adds configuration option to choose between `servlet` (default) and `whiteboard` TCCL. See https://github.com/ops4j/org.ops4j.pax.web/issues/1760#issuecomment-1250772212.

If you uninstall the `tccl-bug-poc` it may take few hundreds of msecs to restart the target context. But anyway, I'll check. Before #1760 (and also without configuring the new `org.ops4j.pax.web.tccl.type` option), TCCL setting is the responsibility of Jetty/Tomcat/Undertow. Pax Web only ensures that the OsgiContextClassLoader contains proper bundles - this was fixed by #1759, but I sense it may not be proper fix... Checking.

**Comment by grgrzybek** [comment]
Hmm, I see the classloader is fine, it refers to the new bundles, but somehow the loading classloader is still the one from first _edition_ of the lib bundle... Checking.

**Comment by qianwch** [comment]
> Hmm, I see the classloader is fine, it refers to the new bundles, but somehow the loading classloader is still the one from first _edition_ of the lib bundle... Checking.

Yes, too strange... If we set the TCCL to Bundle class loader, it is fine.

**Comment by grgrzybek** [comment]
`org.ops4j.pax.web.service.spi.servlet.OsgiServletContextClassLoader` is fine and contains proper bundles, but there's some native/low-level stuff that caches the classloader of first uninstalled `lib1` bundle as `defining` classloader of `org.example.lib1.HelloApiWrapper$MyHello` class.

**Comment by grgrzybek** [comment]
Relevant output of `-verbose:class`:
```
[Loaded org.example.app1.Activator from jar:bundle://2a63595c-216e-4955-a27e-b00046372ff7_87.0:0/!/]
[Loaded org.example.app1.MyServlet from jar:bundle://2a63595c-216e-4955-a27e-b00046372ff7_87.0:0/!/]
[Loaded org.example.lib1.HelloApiFactory from jar:bundle://2a63595c-216e-4955-a27e-b00046372ff7_88.0:0/!/]
[Loaded org.example.lib1.HelloApiWrapper from jar:bundle://2a63595c-216e-4955-a27e-b00046372ff7_88.0:0/!/]
[Loaded org.example.lib1.HelloApiWrapper$HelloApi from jar:bundle://2a63595c-216e-4955-a27e-b00046372ff7_88.0:0/!/]
[Loaded org.example.lib1.HelloApiWrapper$MyHello from jar:bundle://2a63595c-216e-4955-a27e-b00046372ff7_88.0:0/!/]
ClassLoader for HelloApiWrapper is org.example.the-lib1 [88]
ClassLoader for HelloApiWrapper$MyHello is org.example.the-lib1 [88]
[Loaded org.example.app1.Activator from jar:bundle://2a63595c-216e-4955-a27e-b00046372ff7_89.0:0/!/]
[Loaded org.example.app1.MyServlet from jar:bundle://2a63595c-216e-4955-a27e-b00046372ff7_89.0:0/!/]
[Loaded org.example.lib1.HelloApiFactory from jar:bundle://2a63595c-216e-4955-a27e-b00046372ff7_90.0:0/!/]
[Loaded org.example.lib1.HelloApiWrapper from jar:bundle://2a63595c-216e-4955-a27e-b00046372ff7_90.0:0/!/]
ClassLoader for HelloApiWrapper is org.example.the-lib1 [90]
ClassLoader for HelloApiWrapper$MyHello is org.example.the-lib1 [88]
[Loaded org.example.lib1.HelloApiWrapper$HelloApi from jar:bundle://2a63595c-216e-4955-a27e-b00046372ff7_90.0:0/!/]
```

At first installation, app has bundleId=87 and lib has bundleId=88. Then it's 89 and 90 respectively.

However at second request, `org.example.lib1.HelloApiWrapper` is loaded correctly, but it's internal class `org.example.lib1.HelloApiWrapper$MyHello` is still loaded by previous version of `lib` bundle... weird.

**Comment by grgrzybek** [comment]
Initially (at 1st attempt), everything is normal:
```
"qtp332279633-253@8578" prio=5 tid=0xfd nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.lang.ClassLoader.defineClass(ClassLoader.java:754)
	  at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClass(BundleWiringImpl.java:2338)
	  at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClassParallel(BundleWiringImpl.java:2156)
	  at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2090)
[1]	  at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1556)
	  at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
	  at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1976)
	  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	  at org.apache.felix.framework.BundleWiringImpl.getClassByDelegation(BundleWiringImpl.java:1358)
	  at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1612)
[2]	  at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1528)
	  at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
	  at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1976)
	  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	  at org.apache.felix.framework.Felix.loadBundleClass(Felix.java:2116)
	  at org.apache.felix.framework.BundleImpl.loadClass(BundleImpl.java:986)
	  at org.ops4j.pax.web.service.spi.servlet.OsgiServletContextClassLoader.loadClass(OsgiServletContextClassLoader.java:124)
	  at java.lang.Class.forName0(Class.java:-1)
	  at java.lang.Class.forName(Class.java:348)
	  at org.example.lib1.HelloApiWrapper.<clinit>(HelloApiWrapper.java:7)
	  at org.example.lib1.HelloApiFactory.<clinit>(HelloApiFactory.java:4)
	  at org.example.app1.MyServlet.doGet(MyServlet.java:31)
	  at javax.servlet.http.HttpServlet.service(HttpServlet.java:497)
...
```
In `[1]`, the classloader is from `org.example.the-lib1 [94]` and in `[2]` - from `org.example.the-app1 [93]` - typical `Import-Package` scenario.

At 2nd attempt, `org.example.lib1.HelloApiWrapper$MyHello` is not defined - it is returned from existing instance of `OsgiServletContextClassLoader`. That's how classloaders work and the only thing I can do is to change the `OsgiServletContextClassLoader` for a context if any combination of bundles changes...

**Comment by grgrzybek** [comment]
Because ClassLoaders are one of the hardest parts of Java programming, I won't do it today ;)

**Comment by grgrzybek** [comment]
@qianwch hi

I was thinking about your findings (and I appreciate your great investigation) and I'm afraid we have to change few things. Let me summarize:
* with #1759 I've ensured that in Whiteboard scenario (because WAB scenario is more consistent) each web element (servlet/filter/listener/...) registered to the context, adds its bundle to a list of bundles under `OsgiServletContextClassLoader`
* with #1760 I've added `org.ops4j.pax.web.tccl.type` option to choose whether TCCL should be context's `OsgiServletContextClassLoader` (the default setting) or servlet's/filter's classloader

however, #1759 fix caused two problems:
* when two servlets are registered and one is unregistered, the servlet's bundle classloader is removed (no ref counting) - I used trivial implementation - I've created #1772 to fix this, but the fix is not ready yet
* however the more important problem is described in this (#1771) issue you've found. `OsgiServletContextClassLoader` is delegating to a set of bundles and classLoader mechanics comes into play.

Checking [JVM specification, chapter 5.3. Creation and Loading](https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-5.html#jvms-5.3) we have:
* _initiating classloader_ (which is `OsgiServletContextClassLoader` specific to a context and using a set of bundles underneath
* _defining classloader_ which is the bundle classloader

> After creation, a class or interface is determined not by its name alone, but by a pair: its binary name ([§4.2.1](https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-4.html#jvms-4.2.1)) and its defining loader. Each such class or interface belongs to a single run-time package. The run-time package of a class or interface is determined by the package name and the defining loader of the class or interface.

The most important fragment is in section `5.3.2. Loading Using a User-defined Class Loader`:

> […] the Java Virtual Machine determines whether L has already been recorded as an initiating loader of a class or interface denoted by N. If so, this class or interface is C, and no class loading or creation is necessary. 

So when we load `HelloApiWrapper$MyHello` from `OsgiServletContextClassLoader` which delegates to first _incarnation_ of `org.example.the-lib1` bundle (which I added there because of fix for #1759) and then you 1) uninstall the feature, 2) install it again, then without fully replacing `OsgiServletContextClassLoader` (the initiating classloader) which effectively means restart of entire context, next time you load the class, the cached version is used (with _defining_ classloader belonging to uninstalled bundle).
**And I'd heavily would like to avoid it, because now we have very dynamic, fast, reliable and leak-free Whiteboard registration/unregistration**.

So let me present @qianwch what I'd like to do:
* fully revert fix for #1759 (which also means I don't have to fix #1772 - the refcounting)
* encourage you to use the new option `org.ops4j.pax.web.tccl.type=whiteboard`, so TCCL = bundleclassloader of the servlet

I checked this:
```
karaf@root()> config:property-set --pid org.ops4j.pax.web org.ops4j.pax.web.tccl.type whiteboard
```

Then I installed your feature:
```
karaf@root()> feature:uninstall tccl-bug-poc                                                                                                                                                                                               
```

Checked `curl`:
```
$ curl http://localhost:8181/hello1
MyHello: Hi World !
```

See this in console:
```
karaf@root()> ClassLoader for HelloApiWrapper is org.example.the-lib1 [79]                                                                                                                                                                     
ClassLoader for HelloApiWrapper$MyHello is org.example.the-lib1 [79]
```

reinstall the feature:
```
karaf@root()> feature:uninstall tccl-bug-poc                                                                                                                                                                                               
karaf@root()> feature:install tccl-bug-poc                                                                                                                                                                    
```

checked `curl` again and see this in console:
```
karaf@root()> ClassLoader for HelloApiWrapper is org.example.the-lib1 [81]                                                                                                                                                                     
ClassLoader for HelloApiWrapper$MyHello is org.example.the-lib1 [81]
```
which means the class was really loaded+defined by proper classloader of the reinstalled `org.example.the-lib1` bundle.

**Comment by qianwch** [comment]
@grgrzybek I think "org.ops4j.pax.web.tccl.type=whiteboard" works exactly in my expected manner. And I have tested to confirm it.
Now TCCL is the same as ServletContext CL, and jsp feature still work.
 I am wondering whether it is possible to set it as the default value after  @sometime...

**Comment by grgrzybek** [comment]
> I am wondering whether it is possible to set it as the default value after sometime...

I'd keep as is - because of how it'd affect WAR deployments and HttpService registrations. TCCL can't point to single bundle - for SCI purposes for example (even if these are called during initialization), we need to reach to more bundles (like pax-web-jsp).

But let's keep this question open ;)
